// src/components/Footer.vue
<script setup lang="ts">
import { useI18n } from 'vue-i18n'
const {t} = useI18n()
</script>


<template>
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 sm:py-8 lg:py-12 flex items-center justify-between text-sm text-gray-700 border-t border-gray-200">
        <div class="flex flex-wrap items-center space-x-4">
            <p>&copy; <strong>Corentin Le Guen</strong> - {{ t('legal.rights') }}</p>
            <a href="https://github.com/CorentinLeGuen/cleguen.com" target="_blank" class="text-gray-500 text-xs font-light hover:underline">
                {{ t('about.website_sources') }}
            </a>
        </div>
        
        <div class="flex flex-wrap items-center space-x-4">
            <RouterLink to="/legal">
                {{ t('legal.title') }}
            </RouterLink>
        </div>
    </div>
</template>

// src/lib/components/Footer.svelte
<script>
	import { Footer, FooterCopyright, FooterLinkGroup, FooterLink } from 'flowbite-svelte';
	import { t } from '$lib/i18n/config';
</script>

<Footer class="border-t-1 border-gray-100 dark:border-gray-800">
	<div class="w-full mx-auto max-w-screen-xl p-4 space-x-8 flex items-center justify-between">
        <span class="self-center text-sm text-gray-700 dark:text-gray-400">
            &copy; 2025 <a href="/" class="font-semibold">Corentin Le Guen</a> - {$t('translations.legal.rights')} 
        </span>
		<FooterLinkGroup class="flex flex-wrap items-center text-sm text-gray-500 dark:text-gray-400">
			<FooterLink href="/about">{$t('translations.about.title')}</FooterLink>
			<FooterLink href="/legal">{$t('translations.legal.title')}</FooterLink>
		</FooterLinkGroup>
	</div>
</Footer>
