// src/components/Navbar.vue
<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import Language from "@/components/Language.vue";
const { t } = useI18n()
</script>

<template>
    <div class="flex items-center justify-center">
        <RouterLink to="/" class="flex items-center justify-center text-gray-700 hover:text-gray-800 m-2 me-8">
            <img src="@/assets/favicon.svg" alt="logo" class="w-8 me-2.5 drop-shadow"/>
            <p class="font-bold text-xl">cleguen.com</p>
        </RouterLink>
        <RouterLink to="/blog" class="text-gray-700 hover:text-amber-600 font-medium m-2 me-8">
            {{ t('blog.nav') }}
        </RouterLink>
        <Language />
    </div>
</template>

// src/lib/components/Navbar.svelte
<script>
	import { Navbar, NavBrand, NavLi, NavUl, NavHamburger } from 'flowbite-svelte';
	import ThemeToggle from './ThemeToggle.svelte';
    import LanguageSwitcher from './LanguageSwitcher.svelte';
	import { t } from '$lib/i18n/config';
</script>

<Navbar color="form">
	<NavBrand href="/">
		<img src="/favicon.svg" class="me-3 h-6 sm:h-9" alt="Website Logo" />
		<span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">CLeGuen</span>
	</NavBrand>
	<div class="flex md:order-2">
		<ThemeToggle />
        <LanguageSwitcher />
		<NavHamburger />
	</div>
	<NavUl>
		<NavLi href="/blog/">{$t('translations.nav.blog')}</NavLi>
		<NavLi href="/about">{$t('translations.nav.about')} & {$t('translations.nav.contact')}</NavLi>
	</NavUl>
</Navbar>
